name: $(Date:yy.MM.dd)$(Rev:.rr)

stages:
  - template: templates/TemplateWithoutParams.azure-pipelines.yml

  - template: templates/TemplateWithParams.azure-pipelines.yml
    parameters:
      testParam: Hello